### ISSUE TITLE
“和”字拼音转成了han4

### ISSUE THREAD

**Issue by xuchenxing** [GitYCC/g2pW#17]
>>> conv = G2PWConverter(style='pinyin', enable_non_tradional_chinese=True)

>>> conv('我和你')
[['wo3', 'han4', 'ni3']]

如上图， 测试发现“和”字拼音转成了han4

**Comment by jinfagang** [comment]
同

**Comment by yt605155624** [comment]
这个就是台湾话和普通话的区别了，参考 https://www.zhihu.com/question/31151037，[PaddleSpeech](https://github.com/PaddlePaddle/PaddleSpeech/) 中已经针对台湾话和普通话的 diff 对字典进行了修改

**Comment by GitYCC** [comment]
@yt605155624
請問具體是怎麼做的？

**Comment by yt605155624** [comment]
@GitYCC 我们引入 G2PW 之后，用 csmsc 这个数据集为 GroundTruth 跑了个 G2P 的 WER (参考 [xamples/other/g2p](https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/examples/other/g2p) ), 发现比原本使用 pypinyin 要差，这是不符合预期的，对比 badcase 和上述 zhihu 链接，以及日常生活中知道的一些台湾腔和普通话不一样的点，发现几种情况：
1. 个别多音字的发音和普通话不一样
2. 台湾话有的字多音字更多
3. 个别非多音字发音和普通话不一样
于是，我修改了你们的多音字字典和非多音字字典，修改后的模型和字典在 https://paddlespeech.bj.bcebos.com/Parakeet/released_models/g2p/G2PWModel_1.1.zip 可以下载下来和你们原始的字典 diff 一下，并且把某些多音字移出了多音字字典，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/a657cc3e1b5452cc564c9d3ae4bff25717910a49/paddlespeech/t2s/frontend/g2pw/onnx_api.py#L101

**Comment by GitYCC** [comment]
Wow~ Great work

**Comment by dalan2014** [comment]
试了一下，感觉目前效果还是比pypinyin差了一些，还hai老是认成huan，中zhong1老是变成zhong4，着zhe老是变成zhuo

**Comment by leonardmq** [comment]
> 于是，我修改了你们的多音字字典和非多音字字典，修改后的模型和字典在 https://paddlespeech.bj.bcebos.com/Parakeet/released_models/g2p/G2PWModel_1.1.zip 可以下载下来和你们原始的字典 diff 一下，并且把某些多音字移出了多音字字典，参考 https://github.com/PaddlePaddle/PaddleSpeech/blob/a657cc3e1b5452cc564c9d3ae4bff25717910a49/paddlespeech/t2s/frontend/g2pw/onnx_api.py#L101

下载模型的链接似乎已经移动了：  
https://paddlespeech.bj.bcebos.com/Parakeet/released_models/g2p/new/G2PWModel_1.1.zip
