### ISSUE TITLE
錫	ㄒㄧ2？

### ISSUE THREAD

**Issue by langlanglofa** [GitYCC/g2pW#2]
[錫	ㄒㄧ1](https://www.zdic.net/hans/%E9%8C%AB)

**Comment by langlanglofa** [comment]
怎么解决变调问题？

**Comment by GitYCC** [comment]
There is no tone sandhi right now.

**Comment by yt605155624** [comment]
@langlanglofa there are tone_sandhis in PaddleSpeech's TTS, and we are including g2pw as the default g2p now, https://github.com/GitYCC/g2pW/issues/5
