### ISSUE TITLE
inference 60 characters, cost 0.86 sencond on cpu, how to acceleration time

### ISSUE THREAD

**Issue by liuhuang31** [GitYCC/g2pW#4]
hi, 
    Thanks the provided code and model. 
     When i use the g2pw to do g2p, it cost too long time.
       `conv = G2PWConverter(style='pinyin', enable_non_tradional_chinese=True)`

  I inference 60 characters, cost 0.86s on cpu, have any way to accelerate it? Thanks again.

**Comment by yt605155624** [comment]
maybe you can use convert model to onnx and use onnxruntime, check pr in https://github.com/GitYCC/g2pW/issues/5

**Comment by liuhuang31** [comment]
> 

谢谢，对g2pw代码进行了修改：dataloader也进行了相应修改，最后改成直接预测一整句话，速度大概在0.07～0.13s左右。也是在paddle下增加了g2pw选项。

**Comment by yt605155624** [comment]
nice~ I have print the time of G2PWOnnxConverter, the first time of using onnxruntime will be slow (it's onnxruntime's feature)
![image](https://user-images.githubusercontent.com/24568452/183798366-c67e8cda-56f4-4941-af5d-20f57467d9af.png)
I will be appreciated if you can include your perfect improvement into paddlespeech after our onnxruntime version of g2pw merged, and I also looking forward to your pr if you are using paddlespeech TTS :)

**Comment by liuhuang31** [comment]
您好，你的邮件已收到哦，我会尽快回复的。                                                ——刘煌

**Comment by GitYCC** [comment]
> > 
> 
> 谢谢，对g2pw代码进行了修改：dataloader也进行了相应修改，最后改成直接预测一整句话，速度大概在0.07～0.13s左右。也是在paddle下增加了g2pw选项。

@liuhuang31 
Thanks for your response. The feature of "predicting whole sentence in one shot" sounds interesting. 
Could I invite you to give a PR and become a contributor? 
Or, if your time is not available, could you show a piece of codes to help us adding this feature by ourself?

**Comment by liuhuang31** [comment]
> 

Thanks for your response, i want to give a PR, it is much convenient.

**Comment by GitYCC** [comment]
@liuhuang31 Thank you! I am looking forward your PR.

**Comment by beyondguo** [comment]
> 

Hi, could you please tell me how to use `G2PWOnnxConverter` ? I didn't find it in the code.

**Comment by liuhuang31** [comment]
> 

Hi, the newest code default use OnnxConverter model to predict, so just install the newest code and use it.

**Comment by liuhuang31** [comment]
> > 
> 
> Hi, could you please tell me how to use `G2PWOnnxConverter` ? I didn't find it in the code.

解决了嘛，没解决话是遇到啥问题了呢～

**Comment by liuhuang31** [comment]
> > 
> 
> Hi, could you please tell me how to use `G2PWOnnxConverter` ? I didn't find it in the code.

解决了嘛，没解决话是遇到啥问题了呢～

**Comment by liuhuang31** [comment]
> > 
> 
> Hi, could you please tell me how to use `G2PWOnnxConverter` ? I didn't find it in the code.

解决了嘛，没解决话是又遇到啥问题了呢～ @beyondguo

**Comment by beyondguo** [comment]
@liuhuang31 liu
Hi
我是这几天直接pip安装的，应该就是最新版了。但感觉预测速度还是比较慢：
```python
from g2pw import G2PWConverter
conv = G2PWConverter(style='pinyin', enable_non_tradional_chinese=True)

%timeit conv('然而，他红了20年以后，他竟退出了大家的视线。')
```
平均时长：
```
701 ms ± 30.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

不是初次加载模型，是每次跑都差不多这个时间。我现在的需求是对一个大语料库做注音，所以希望推理速度快一点。

**Comment by liuhuang31** [comment]
> 

@beyondguo 你可以看看我的pull request, 我在旧的版本上，60个字能达到0.08-0.13秒。

**Comment by beyondguo** [comment]
@liuhuang31 
我刚刚下载了你的版本（https://github.com/liuhuang31/g2pW），测试了一下，一样的代码：
```python
>>> %timeit conv('然而，他红了20年以后，他竟退出了大家的视线。')
<<< 1.44 s ± 39.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
然而更慢了，不知道我是哪里用错了吗[Lol]

**Comment by liuhuang31** [comment]
@beyondguo 应该没用对，等有时间再跟你讨论，我先忙工作事情，比较紧急

**Comment by JohnHerry** [comment]
确实慢，有办法做模型精简吗？onnx也慢。

**Comment by liuhuang31** [comment]
> 
g2pw每次预测会先做句子分词，然后一句话可能会分成10次，那么就要调用10次去预测。
没有做模型精简，我是直接修改代码，直接一句话输入进去，只预测一次，所以速度很快。
